apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-harbor-trivy-0
  labels: 
    app: pvc-harbor-trivy-0
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  local:
    path: /opt/harbor/trivy
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - worker-1
  storageClassName: local-storage 
