apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-harbor-trivy-0
  namespace: harbor
  labels:
    app: pv-harbor-trivy-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 15Gi
  volumeName: pv-harbor-trivy-0