apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-harbor-registry
  namespace: harbor
  labels:
    app: pv-harbor-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-harbor-registry
